# Generated by Django 4.2.2 on 2023-07-06 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urls',
            name='processed_urls',
            field=models.ManyToManyField(blank=True, to='filter.urls'),
        ),
    ]
