# Generated by Django 4.2.2 on 2023-07-06 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0002_urls_processed_urls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urls',
            name='processed_urls',
        ),
    ]
