# Generated by Django 4.2.2 on 2023-07-17 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0006_remove_urls_processed_urls_remove_urls_total_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='urls',
            name='status',
            field=models.CharField(default='Null', max_length=255),
            preserve_default=False,
        ),
    ]
